### ISSUE TITLE
Unclear documentation on how to decode Array of Map values.

### ISSUE THREAD

**Issue by martiwi** [myfreeweb/SwiftCBOR#15]
With the following CBOR binary message (hex string):
`82A102A361760C6175016174187BA103A3617662323361750261741901C8`

Which correspond to the following JSON:
```
[
  {
    2: {
      "v": 12,
      "u": 1,
      "t": 123
    }
  },
  {
    3: {
      "v": "23",
      "u": 2,
      "t": 456
    }
  }
]
```

From the documentation it is not clear how to read it in an efficient and clean way. The way it is right now:
```
            cbor = try CBORDecoder.init(input: data).decodeItem()
            var index = 0
            // We loop over each item from the array.
            while let item = cbor![CBOR.init(integerLiteral: index)] {
                index = index + 1
                // Here I have to know in advance that on first item I will get it like that
                // let first = item[2]
                // and that the second one I will get it by doing
                // let second = item[3]
            }
```
As 2 and 3 are variable as well, which are 4 byte long, looping over each possible value is not a solution.

Any thoughts ?

**Comment by myfreeweb** [comment]
After you call `CBORDecoder.init(input: data).decodeItem()` it's already completely decoded into something like

```swift
CBOR.array([
  CBOR.map([
    CBOR.unsignedInt(2) : CBOR.map([ CBOR.utf8string("v") : CBOR.unsignedInt(12), … ])
  ]),
  CBOR.map([
    CBOR.unsignedInt(3) : CBOR.map([ CBOR.utf8string("v") : CBOR.unsignedInt(23), … ])
  ])
])
```

So it's just a normal data structure, you can traverse it however you want, you're not streaming it, you're not required to go over arrays sequentially or anything

**Comment by martiwi** [comment]
Yes, that is the issue, it is not clear for me how to traverse it.
Based on the code example I've gave how will you get the `CBOR.map([ CBOR.utf8string("v") : CBOR.unsignedInt(12), … ]` object without knowing the key value.
Meaning `CBOR.unsignedInt(2)` is not something static. It goes from 0x00 to 0xFFFFFFFF.
Doing something like that seems impossible at first:
```
for (key, value) in item {
    // todo
}
```

**Comment by myfreeweb** [comment]
CBOR.map contains a regular Swift map, of course you can just take it and loop over its key-value pairs.

Something like

```swift
if case .map(let myMap) = item {
  for (key, value) in myMap {
  }
}
```

(I haven't touched Swift in a long time, I'm writing this blind, might not be the exact syntax, but that's the idea. You should learn more about [pattern matching](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Patterns.html).)

**Comment by martiwi** [comment]
Thanks for pointing me in the right direction.
