### ISSUE TITLE
Question on including [UInt8] data into encode()

### ISSUE THREAD

**Issue by keithle888** [myfreeweb/SwiftCBOR#19]
Hello, may I ask how I can include [UInt8] data as part of the cbor message?

**Comment by myfreeweb** [comment]
Hi.

There's an example of encoding `[UInt8]` as byte string in the readme:

```swift
let byteString: [UInt8] = [0x01, 0x02]
CBOR.encode(byteString, asByteString: true)
```

If you want it encoded as an array (less efficient), just don't add `asByteString: true`.

If you want a byte string inside of some structure, create a `CBOR.byteString` inside your `CBOR` tree. (See the `struct MyStruct: CBOREncodable` example in the readme.)

**Comment by keithle888** [comment]
Hey! Thanks for the quick reply.

Yes, I've been using this as reference.
I do 
````
public func encode() -> [UInt8] {
    let cborWrapper = CBOR(dictionaryLiteral:
            ("x", CBOR(integerLiteral: self.x)),
            ("y", CBOR(stringLiteral: self.y)))
        return cborWrapper.encode()
    }
````

This is what my code looks like:
````
    func encode() -> [UInt8] {
        let cborWrapper = CBOR(dictionaryLiteral:
                            (CBOR(integerLiteral: 1), CBOR(integerLiteral: 1001)),
                            (CBOR(integerLiteral: 2), CBOR(integerLiteral: self.some_int32)),
                            (CBOR(integerLiteral: 3), self.hasSome_int8() ? CBOR(integerLiteral: self.some_int8!) : CBOR(nilLiteral: ())),
                            (CBOR(integerLiteral: 4), CBOR(booleanLiteral: self.some_bool))
        )
        return cborWrapper.encode()
    }
````

I am trying to include a class member self.someByteArray: [UInt8]? in the dictionary.

**Comment by myfreeweb** [comment]
Yeah just use `CBOR.byteString([0x...])` as one of the values

**Comment by keithle888** [comment]
Thanks for the prompt reply. Thats solved my problem :)
