### ISSUE TITLE
Ordering of keys in encoded map.

### ISSUE THREAD

**Issue by keithle888** [myfreeweb/SwiftCBOR#21]
Hello!

I using this example as reference:
```
public func encode() -> [UInt8] {
        let cborWrapper = CBOR(dictionaryLiteral:
            ("x", CBOR(integerLiteral: self.x)),
            ("y", CBOR(stringLiteral: self.y)))
        return cborWrapper.encode()
    }
```

With my code: 
```
    public func encode() -> [UInt8] {
        let cborWrapper = CBOR(dictionaryLiteral:
                                (CBOR(integerLiteral: 0), CBOR(integerLiteral: 1001)),
                               (CBOR(integerLiteral: 1), CBOR(integerLiteral: self.some_int32)),
                               (CBOR(integerLiteral: 2), self.hasSome_int8() ? CBOR(integerLiteral: self.some_int8!) : CBOR(nilLiteral: ())),
                               (CBOR(integerLiteral: 3), CBOR(booleanLiteral: self.some_bool)),
                               (CBOR(integerLiteral: 4), self.hasSome_btyearray() ? CBOR.byteString(self.some_bytearray!) : CBOR(nilLiteral: ())),
                               (CBOR(integerLiteral: 5), self.hasSome_string() ? CBOR(stringLiteral: self.some_string!) : CBOR(nilLiteral: ()))
        )
        return cborWrapper.encode()
    }
```
The hex it generates is : A60441FF0566737472696E670208001903E901182003F5

My question is, would it be possible to get the keys (integerLiteral) ordered in ascending order?

Thank you very much and any advice would be appreciated.

**Comment by keithle888** [comment]
Also an additional question:

How do I get an Int value from a CBOR.unsignedInt ?

**Comment by myfreeweb** [comment]
Hm, you actually can easily encode the map in-order manually.

Instead of building an outer CBOR enum with `dictionaryLiteral`, just directly return the bytes for the map.

[Encoding a map is simple](https://github.com/myfreeweb/SwiftCBOR/blob/c7f1ff41d41ca698578318df870198634a0cdd15/SwiftCBOR/CBOREncoder.swift#L118), you just encode the count, OR the first byte with `0b101_00000`, and encode the key-value pairs.

Something like

```swift
    public func encode() -> [UInt8] {
        var res: [UInt8] = Int(3).encode() // well, your actual count
        res[0] = res[0] | 0b101_00000
        res.append(contentsOf: 0.encode())
        res.append(contentsOf: 1001.encode())
        res.append(contentsOf: 1.encode())
        res.append(contentsOf: self.some_int32.encode())
        res.append(contentsOf: 2.encode())
        res.append(contentsOf: self.hasSome_int8() ? CBOR(integerLiteral: self.some_int8!) : CBOR(nilLiteral: ())) // CBOR enum itself is encodable
        return res
    }
```

**Comment by keithle888** [comment]
Thanks alot for the guide on the ordering of the map! I've managed to implement it. 

I'm still relatively new to Swift, so I'm reading up on Swift pattern matching to get the UInt64 value.

Again, thanks alot for the quick replies :)

**Comment by keithle888** [comment]
Thanks alot for your help! I managed to get pattern matching to work for extracting the values from a CBOR object.
