### ISSUE TITLE
Casting utf8string, unsignedInt and ByteString to respective types.

### ISSUE THREAD

**Issue by keithle888** [myfreeweb/SwiftCBOR#23]
Can I get clarification on how to cast the mentioned CBOR types to String, Int and [UInt8] respectively? The documentation is a tad unclear on how to achieve that. Thanks!

**Comment by myfreeweb** [comment]
I answered this in #21: you don't cast them, you pattern match on them like this:

```swift
if case let CBOR.unsignedInt(int_val) = cbor_val {
    do_things_with(int_val);
}
```

or `switch`, or `guard case let`, or whatever.

You can learn pattern matching with [this series of tutorials](https://alisoftware.github.io/swift/pattern-matching/2016/05/16/pattern-matching-4/).
