### ISSUE TITLE
Issues encoding Int

### ISSUE THREAD

**Issue by keithle888** [myfreeweb/SwiftCBOR#26]
Hello! 

I've noticed a peculiar behavior when calling .encode() on Integers. Not sure if it's expected behavior.

My code:
````
//Start testing random
        for i in 0...100 {
            print("Number: \(i)")
            print("Hex: \(i.encode().hexa)")
            print("")
        }
````

And a sample of the output I'm getting is:
````
Number: 20
Hex: 14

Number: 21
Hex: 15

Number: 22
Hex: 16

Number: 23
Hex: 17

Number: 24
Hex: 1818

Number: 25
Hex: 1819

Number: 26
Hex: 181A

Number: 27
Hex: 181B

Number: 28
Hex: 181C

Number: 29
Hex: 181D
````

Hexa:
````
extension Collection where Iterator.Element == UInt8 {
    var data: Data {
        return Data(self)
    }
    var hexa: String {
        return map{ String(format: "%02X", $0) }.joined()
    }
}
````

**Comment by myfreeweb** [comment]
Hi, this is exactly how CBOR is supposed to work, try entering these hex codes into the [playground](http://cbor.me/) :)

Quoting the [spec](https://tools.ietf.org/html/rfc7049#section-2):

> When the value of the additional information is less than 24, it is directly used as a
   small unsigned integer.  When it is 24 to 27, the additional bytes
   for a variable-length integer immediately follow; the values 24 to 27
   of the additional information specify that its length is a 1-, 2-,
   4-, or 8-byte unsigned integer, respectively.
