### ISSUE TITLE
Issues decoding hex string

### ISSUE THREAD

**Issue by joaopedro1520** [myfreeweb/SwiftCBOR#27]
Hello,
I'm trying to start encoding/decoding CBOR messages and I'm running into issues trying to decode.

I have the following hex data - 9f1b00000164a8e830608b1905340069302e332e302d64657669302e332e302d64657665342e302e326f38363631393130333136343936343373383933353130313831313534323038323534376b4d393546415230324130387641584e5f322e33325f333333375f313530313038303103008719057608f6f6f6f6f6831905600701ff

which is not decoding correctly according to cbor.me. Here is my code. I guess I'm converting it wrong? 
Can you provide some help? thank you

```
       let info3:[UInt8] = Array(Data(hex: "9f1b00000164a8e830608b1905340069302e332e302d64657669302e332e302d64657665342e302e326f38363631393130333136343936343373383933353130313831313534323038323534376b4d393546415230324130387641584e5f322e33325f333333375f313530313038303103008719057608f6f6f6f6f6831905600701ff"))
        
        
        let decoded = try! CBOR.decode(info3)
        print(decoded)
```

**Comment by myfreeweb** [comment]
Please explain what exactly "not decoding correctly" means.

(Also from what I could find, the `hex:` constructor is on Array, not Data: `Array<UInt8>(hex: "9f1b0...")`)

**Comment by joaopedro1520** [comment]
I'm sorry that's not what I meant. What I meant is the issue is somehow I'm not converting the hex string to [UInt8] correctly. 
Also  passing `Array<UInt8>(hex: "9f1b0..."))` it causes an exception inside the decoder. 
When converting to Uint8 like [UInt8]("9f1b0...".utf8) it returns a result but it's not the expected one.
So my question is how should the hex string be converted/used to pass as parameter to the decoder?
Thanks

**Comment by myfreeweb** [comment]
> an exception inside the decoder

Please show the exception.

(I hope you've tried it with your actual hex string, without the `...` :))

**Comment by joaopedro1520** [comment]
Yes of course :) 
But its possible to be using the decoder with a string like this? because in all your test examples you are using `CBORDecoder(input:` **[0x7a, 0x00, 0x00, 0x00, 3, 0x41, 0x42, 0x43]**`).decodeItem()`

![captura de ecra 2018-07-18 as 17 00 19](https://user-images.githubusercontent.com/20184389/42893416-27979242-8aac-11e8-9c60-9c4144bfd38f.png)

**Comment by myfreeweb** [comment]
Creating an Array with the `hex:` argument literally decodes `"7a00…"` into `[0x7a, 0x00, …]`. The decoder just needs *an array of bytes*, it doesn't care about where it came from, how you decoded it or whatever.

The exception is a breakpoint. You have breakpoints set on lines 74 and 75, have you tried removing them?

**Comment by joaopedro1520** [comment]
Yeah no breakpoints are active, the exception is still the same

**Comment by joaopedro1520** [comment]
Update: removed code optimization and the exception is the following   - Fatal error: Not enough bits to represent a signed value

**Comment by myfreeweb** [comment]
Ooh, that looks a lot more helpful.

I noticed on the screenshot, you have an old version of SwiftCBOR. This code has changed. Try current git master.

Also, [here](https://stackoverflow.com/a/42731691) is a hex decoder that works. I'm not sure why the built-in one is not available for me (on Linux). Is there a built-in one? idk.

**Comment by joaopedro1520** [comment]
Thanks for the help and noticing the code was old ( I installed the cocoa pods version btw) just added the version from master and it just worked still same solution

```
        let strinx  = Array<UInt8>(hex:  "9f1b00000164a8e830608b1905340069302e332e302d64657669302e332e302d64657665342e302e326f38363631393130333136343936343373383933353130313831313534323038323534376b4d393546415230324130387641584e5f322e33325f333333375f313530313038303103008719057608f6f6f6f6f6831905600701ff")
        
        let decoded = try! CBOR.decode(strinx)
        print(decoded)
        
```

Thanks for the help and sorry for the trouble :)

**Comment by myfreeweb** [comment]
Yeah I guess I should make a 0.3 release already…
