### ISSUE TITLE
Encoding arrays of multiple types

### ISSUE THREAD

**Issue by joaopedro1520** [myfreeweb/SwiftCBOR#28]
Hello, 
Is it possible to encode an array of type Any? 
I would like to encode array with multiple objects but from the examples its just possible to encode arrays of same type?

Trying to encode an array like this 

`        let barr = [2147483647,[1332, 0, "0.3.0-dev", "0.3.0-dev", "4.0.2", "866191031649643", "8935101811542082547", "M95FAR02A08","AXN_2.32_3337_15010801", 3, 0],[1398, 8],[1376, 7, 1]] as [Any]`

Thanks

**Comment by myfreeweb** [comment]
Yeah, you can wrap each value with `CBOR.something` wrappers, and then you have `[CBOR]` which is encodable :)

That's actually briefly mentioned in the readme:

> In some cases it may be necessary to create a CBOR intermediate representation before encoding. For example, if you want to encode an array or dictionary containing heterogeneous types, as is common for JSON-like objects, you can't use native Swift maps yet

**Comment by joaopedro1520** [comment]
You mean something like this? 

`CBOR.init([CBOR.init([CBOR.init(1332), CBOR.init(0), CBOR.init("0.3.0-dev"), CBOR.init("0.3.0-dev"), CBOR.init("4.0.2"), CBOR.init("866191031649643"), CBOR.init("8935101811542082547"), CBOR.init("M95FAR02A08"),CBOR.init("AXN_2.32_3337_15010801"), CBOR.init(3), CBOR.init(0)]),CBOR.init([CBOR.init(1398), CBOR.init(8)]),CBOR.init([CBOR.init(1376), CBOR.init(7), CBOR.init(1)])])`

**Comment by myfreeweb** [comment]
Well, kinda, but it shouldn't look that ugly. If you're getting data from somewhere, `.map` over the array. If you're creating the array with literals, the constructors (at least for simple values) should apply automatically. Something like `CBOR.array(["abc", 123])` should work I think

**Comment by joaopedro1520** [comment]
It worked. Thanks for the help
