### ISSUE TITLE
Decoding issue

### ISSUE THREAD

**Issue by philips77** [myfreeweb/SwiftCBOR#29]
Hi,

I'm trying to decode the following CBOR message:

```
BF                                      # map(*)
   63                                   # text(3)
      6F6666                            # "off"
   00                                   # unsigned(0)
   64                                   # text(4)
      64617461                          # "data"
   59 012C                              # bytes(300)
      4C6F72656D20697073756D20646F6C6F722073697420616D65742C20636F6E73656374657475
722061646970697363696E6720656C69742E205175697371756520657820616E74652C2073656
D7065722075742066617563696275732070686172657472612C20616363756D73616E20657420
61756775652E20566573746962756C756D2076756C70757461746520656C6974206C6967756C
612C2065752074696E636964756E74206F726369206C6163696E696120717569732E2050726F6
96E207363656C6572697371756520647569206174206D61676E6120706C6163657261742C2069
6420626C616E6469742066656C6973207665686963756C612E204D616563656E617320616320
6E69736C2061206F64696F2076617269757320636F6E64696D656E74756D206C # "Lorem ipsum 
dolor sit amet, consectetur adipiscing elit. Quisque ex ante, semper ut faucibus pharetra, accumsan 
et augue. Vestibulum vulputate elit ligula, eu tincidunt orci lacinia quis. Proin scelerisque dui at 
magna placerat, id blandit felis vehicula. Maecenas ac nisl a odio varius condimentum l"
   62                                   # text(2)
      7263                              # "rc"
   00                                   # unsigned(0)
   63                                   # text(3)
      6C656E                            # "len"
   19 012C                              # unsigned(300)
   FF                                   # primitive(*)
```
Here's written as HEX:
BF636F666600646461746159012C4C6F72656D20697073756D20646F6C6F722073697420616D65742C20636F6E73656374657475722061646970697363696E6720656C69742E205175697371756520657820616E74652C2073656D7065722075742066617563696275732070686172657472612C20616363756D73616E2065742061756775652E20566573746962756C756D2076756C70757461746520656C6974206C6967756C612C2065752074696E636964756E74206F726369206C6163696E696120717569732E2050726F696E207363656C6572697371756520647569206174206D61676E6120706C6163657261742C20696420626C616E6469742066656C6973207665686963756C612E204D616563656E6173206163206E69736C2061206F64696F2076617269757320636F6E64696D656E74756D206C62726300636C656E19012CFF
[Link to CBOR.me](http://cbor.me/?bytes=BF(63(6F6666)-00-64(64617461)-59.012C(4C6F72656D20697073756D20646F6C6F722073697420616D65742C20636F6E73656374657475722061646970697363696E6720656C69742E205175697371756520657820616E74652C2073656D7065722075742066617563696275732070686172657472612C20616363756D73616E2065742061756775652E20566573746962756C756D2076756C70757461746520656C6974206C6967756C612C2065752074696E636964756E74206F726369206C6163696E696120717569732E2050726F696E207363656C6572697371756520647569206174206D61676E6120706C6163657261742C20696420626C616E6469742066656C6973207665686963756C612E204D616563656E6173206163206E69736C2061206F64696F2076617269757320636F6E64696D656E74756D206C)-62(7263)-00-63(6C656E)-19.012C-FF))

The parser crashes when trying to decode the byte array ("data" field) on:
```swift
private func readUInt<T: UnsignedInteger>(_ n: Int) throws -> T {
        return UnsafeRawPointer(Array(try istream.popBytes(n).reversed())).load(as: T.self)
}
```
with the following error:
**Thread 8: Simultaneous accesses to 0x1c0270690, but modification requires exclusive access**
I'm using ` payload = try CBOR.decode([UInt8](payloadData!))` to parse the message.

CC: @bgiori

**Comment by philips77** [comment]
FYI: iPhone 6 Plus, Swift 4.1, library source code copied to the project.

**Comment by philips77** [comment]
After following this advice: https://stackoverflow.com/a/48240862/2115352 it seems to work.

**Comment by myfreeweb** [comment]
> library source code copied to the project

From git master, right?

We've had that before: #8 #9…

**Comment by philips77** [comment]
Right... so I guess I have to split another line into two. Consider as fixed, but plenty of other lines require splitting :)

**Comment by bgiori** [comment]
@philips77 I think the copied-in version in mcumgr is old...my mistake. 

See https://github.com/myfreeweb/SwiftCBOR/pull/13
