### ISSUE TITLE
Encoder missing

### ISSUE THREAD

**Issue by ankitsainisoftobiz** [myfreeweb/SwiftCBOR#3]
CBOR encoder is missing here , Only you can find decoder

**Comment by myfreeweb** [comment]
Yes. I haven't implemented the encoder. It's marked as TODO in the README

**Comment by TeiShim** [comment]
Hello, myfreeweb. Do you have a plan to implement the encoder for iOS? If you have the plan, when are you going to make it? If you have not yet, would you please introduce the site including the CBOR encoder for iOS?

**Comment by myfreeweb** [comment]
When I have time.

Would be nice if someone else made the encoder and sent a pull request ;-)

> introduce the site including the CBOR encoder

What does this mean?

**Comment by TeiShim** [comment]
I mean... do you know the (another) web site related to CBOR encoder for iOS?

**Comment by myfreeweb** [comment]
No. I've started this library because there were none.

**Comment by myfreeweb** [comment]
Fixed by #4
