### ISSUE TITLE
Request: Support for binary UUID

### ISSUE THREAD

**Issue by dhiraj** [myfreeweb/SwiftCBOR#30]
It would be awesome if you added support for UUIDs as per https://github.com/lucas-clemente/cbor-specs/blob/master/uuid.md

I'm willing to code support myself, tried using the custom tag support as well but couldn't. Please help, thanks!

I'm able to get a UUID's representation as [UInt8] but I can't figure out what to do next after that.

**Comment by dhiraj** [comment]
That doesn't compile: 
`Type 'CBOR' has no member 'Tag'`

**Comment by myfreeweb** [comment]
hm, you're not using version 0.2.0, are you? make sure you're on git master

**Comment by dhiraj** [comment]
Indeed! That worked, thanks!

I did not even realize that I was missing so much code in the library. Perhaps you should include this pod line in the README?

`pod 'CBOR', :git => 'https://github.com/myfreeweb/SwiftCBOR'`

I'm continuing to look at UUIDs support. When I figure out decoding as well, would you like me to make a pull request to add it into CBOR as a supported Tag value?

**Comment by myfreeweb** [comment]
> as a supported Tag value

Like `static let uuid = CBOR.Tag(rawValue: 37)`? Yeah, of course
