### ISSUE TITLE
All CBOR.Tag static constants need to be public?

### ISSUE THREAD

**Issue by dhiraj** [myfreeweb/SwiftCBOR#31]
When I try to access `CBOR.Tag.uri` from my code, I get this compile error from my Xcode:
`'uri' is inaccessible due to 'internal' protection level`.

Don't those static let statements need to have a `public` in front of them? I'm using Xcode 9.4.1.

Sample full statement looks like this:
`CBOR.tagged(CBOR.Tag.uri, ...)`

Or are these supposed to be used in a different way that I haven't wrapped my head around, yet?

**Comment by myfreeweb** [comment]
Should look like `CBOR.tagged(.uri, ...)` which is a short form of the above (I think??)

Yeah of course they should be public

**Comment by dhiraj** [comment]
K, I'm sending a pull request with this included as well.
