### ISSUE TITLE
Tag release for CocoaPods

### ISSUE THREAD

**Issue by bgiori** [myfreeweb/SwiftCBOR#33]
Hi Greg,

I will be using SwiftCBOR in a framework that I am helping build. The package manager we have chosen is CocoaPods which unfortunately does not allow pulling in source dependencies in the podspec (this issue was also brought up in #7). 

Since there have been a number of changes since `0.2.0`, could you tag a new release? 

Thanks,
Brian

**Comment by myfreeweb** [comment]
Does cocoapods just need a git tag in the git repo, or something else?

**Comment by bgiori** [comment]
I am by no means a CocoaPod expert, but based on this line in the podspec,

```
s.source = { :git => 'https://github.com/myfreeweb/SwiftCBOR.git', :tag => 'v0.2.0' }
```

It looks like it is referring to a specific git tag (not necessarily a github release) when pulling in the source. You may be able to specify a specific commit `:commit => 'xxxxxxxxxx'` but (a) I'm not sure that will work, and (b) it probably best practice to match the version of the pod and the most recent tag.

So to answer your question, yeah, just a git tag :)

**Comment by myfreeweb** [comment]
I tagged `v0.3.0`. But looking at past discussions, looks like it (the updated podspec) actually needs to be submitted to cocoapods itself. @brycehammond?

> does not allow pulling in source dependencies in the podspec (this issue was also brought up in #7)

looking at #7, it *does* allow git dependencies?? just needed to figure out the pod name

**Comment by brycehammond** [comment]
I can update the podspec and push up the pod.  @myfreeweb Currently the pod is 'CBOR', is there any objection to changing that to 'SwiftCBOR'?  PR to come

**Comment by brycehammond** [comment]
@myfreeweb here is the PR: https://github.com/myfreeweb/SwiftCBOR/pull/34.  Once approved can you tag it with v0.3.1

**Comment by bgiori** [comment]
@brycehammond @myfreeweb Thanks guys!
