### ISSUE TITLE
Decoding Example

### ISSUE THREAD

**Issue by adityaxavier** [myfreeweb/SwiftCBOR#36]
Hi,

Am new to swift / iOS development in general. I have been able to use the Encoding implementation of SwiftCBOR without much trouble. However I have not been able to get the decoding done.

I have reached the statement 
let decode = try! CBOR.decode(responseCMD)

However, am not able to understand how to break that data down further.

It would be great if you can provide working example in the Decoding tests you have written / provide a simple example of how to do that.

**Comment by myfreeweb** [comment]
Just [match](https://alisoftware.github.io/swift/pattern-matching/2016/05/16/pattern-matching-4/) on the [CBOR enum](https://github.com/myfreeweb/SwiftCBOR/blob/4ca611b56917aa5db1eea843956cb5e276cad68d/Sources/SwiftCBOR/CBOR.swift#L6-L19). (also the `[]` operator works for when you expect a value to be an array or map.)

Here's a very old example (variants are lowercase now, something else probably changed as well): https://github.com/myfreeweb/freepass/blob/master/ios/Freepass/Freepass/Field.swift but I haven't actually used SwiftCBOR for anything else :D
