### ISSUE TITLE
Info.plist key: CFBundleVersion

### ISSUE THREAD

**Issue by Capred** [myfreeweb/SwiftCBOR#45]
When I'm trying to upload my app using SwiftCBOR, Apple displays an error message:

This bundle Payload/xxxx.app/Frameworks/SwiftCBOR.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

I'm using Carthage, XCode 10.2 and Swift5.

How can I fix it ?
Thanks

**Comment by ayechanpyaesonework** [comment]
Same issue. any progress?

**Comment by ayechanpyaesonework** [comment]
Hi I managed to fix it by updating info.plist inside the SwiftCBOR.framework. Thanks you

**Comment by ramakula** [comment]
<img width="869" alt="Screen Shot 2020-04-07 at 12 40 51 PM" src="https://user-images.githubusercontent.com/2745769/78712183-1427c180-78cd-11ea-82eb-6821c4b91e56.png">

Current project version is empty on all targets. This is what used in info plist. Can someone add it and fix it?

**Comment by hamchapman** [comment]
This should have been fixed by #54 

Let me know if it's still not working for you (if you're able to test using `master` anyway)
