### ISSUE TITLE
Parsing error with 0.4.2

### ISSUE THREAD

**Issue by schlachtzeuger** [myfreeweb/SwiftCBOR#47]
Hi there,

I just upgraded my project from 0.3.0 to 0.4.2 and I got an error decoding the following sequence:

bf186564 67766572 18666a6f 45545166 73714c5a 33c11867 1a5685c1 8019012d 9f19015f 18cbf4ff 19012e9f f5ff1901 2f9f0af5 ff190130 9f020004 f4ff1901 319f01f4 ff190132 64495345 4f190133 68697365 6f2d3030 42ff>

The error message is:

Fatal error: unexpected enum case while switching on value of type '(CBOR, CBOR)'

**Comment by mbalex99** [comment]
@schlachtzeuger what was the exact function you were trying to run?

**Comment by schlachtzeuger** [comment]
Hi @mbalex99, sorry for the late reply! I'm trying to do CBOR.decode([Uint8])

**Comment by schlachtzeuger** [comment]
FYI, with 0.4.3 I was able to parse the data correctly!
