### ISSUE TITLE
No Cocoapod has been submitted for this repo

### ISSUE THREAD

**Issue by TheMadBug** [myfreeweb/SwiftCBOR#7]
Hi guys,
Looks like really good work you've done here.
I've noticed the project comes with a podspec file but no Cocoapod has been submitted.

Is this something you'd be open to doing?
Cheers

**Comment by myfreeweb** [comment]
Eh… Don't want to deal with *another* package repo. I don't even have a Mac right now :D 
Why not just use `pod 'SwiftCBOR', :git => 'https://github.com/myfreeweb/SwiftCBOR'`? (Or switch to [Carthage](https://github.com/Carthage/Carthage))

**Comment by TheMadBug** [comment]
Heya,
I'm making a small internal pod for work that relies on SwiftCBOR which makes it slightly more complicated but it can still be worked around.
Regardless, I can respect you'd rather work on code than package managers. Cheers.

**Comment by satori-ytolstoguzov** [comment]
Btw `pod 'SwiftCBOR', :git => 'https://github.com/myfreeweb/SwiftCBOR'` failes with error:
```
Pre-downloading: `SwiftCBOR` from `https://github.com/myfreeweb/SwiftCBOR`
[!] Unable to find a specification for 'SwiftCBOR'.
```

**Comment by myfreeweb** [comment]
I guess it should be just `CBOR` since the file is called that? https://github.com/myfreeweb/SwiftCBOR/blob/master/CBOR.podspec

**Comment by satori-ytolstoguzov** [comment]
You are right.

**Comment by brycehammond** [comment]
I'm happy to take on the onus of submitting this as a cocoapod.  There's been some great work since the 0.1 tag, so maybe push a 0.2 tag and we can submit that? I can update the podspec (with a PR) and submit if you can push a tag.

**Comment by myfreeweb** [comment]
Sure thing. Now tagged.

**Comment by brycehammond** [comment]
Submitted to cocoapods.  I can add you as an owner if you want to ```pod trunk register greg@unrelenting.technology 'Greg'```
